[project]
profile = rust

[rust]
image = rust:latest

[alias:build]
desc = Compile in debug mode.
cmd = rustup default nightly && cargo build

[alias:run]
desc = Compile in debug mode.
cmd = rustup default nightly && cargo run

[alias:ex]
desc = Run dialog example.
cmd = cargo run --example
interactive = true

[copilot]
image = debian:trixie-slim

[alias:add-deps]
desc = Install dependencies.
cmd = apt-get update && apt-get install -y curl git && apt-get purge && apt-get autoremove && apt-get autoclean && apt-get clean
hidden = true

[alias:add-copilot]
desc = Install dependencies.
cmd = curl -fsSL https://gh.io/copilot-install | bash
hidden = true

[alias:run-copilot]
desc = Run copilot.
cmd = copilot
env = COPILOT_GITHUB_TOKEN
interactive = true
hidden = true

[alias:run]
desc = Run copilot.
pipeline = add-deps,add-copilot,run-copilot
