history_length = 30
delay_afer_connect = 500
interval_ms = 500
contiguous_memory = []

[definitions.coil]
slave_id = 1
read_code = 1
address = 0
length = 1
access = "ReadWrite"
type = "U16"

[definitions.discrete_input]
slave_id = 1
read_code = 2
address = 1
length = 1
access = "ReadWrite"
type = "U16"

[definitions.input_register]
slave_id = 1
read_code = 3
address = 2
length = 1
access = "ReadWrite"
type = "U16"

[definitions.holding_register]
slave_id = 1
read_code = 4
address = 3
length = 1
access = "ReadWrite"
type = "U16"

[definitions.evse_state]
slave_id = 1
read_code = 4
address = 5
length = 1
access = "ReadWrite"
type = "I16"
values = [ {name = "waiting", value = 0}, {name = "plugged", value = 1}, {name = "charging", value = 2}, {name = "finishing", value = 3}, {name = "error", value = -1 }]

[definitions.expression]
slave_id = 1
read_code = 2
address = 10
length = 10
access = "ReadWrite"
type = "PackedAscii"
virtual = true
on_update = """
local value = C_Register:GetInt("input_register")
C_Register:Set("expression", "Tag: " .. value)
 """
