name: Nightly

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update nightly tag
        uses: EndBug/latest-tag@latest
        if: github.ref == 'refs/heads/main'
        with:
          tag-name: nightly
